# Generated by Django 5.1.4 on 2025-04-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
